### ISSUE TITLE
app_yml_path default value

### ISSUE THREAD

**Issue by slively** [MVPStudio/build_setup#12]
for the `app_yml_path` argument give it a default value of `./.mvpstudio/config.tml`

**Comment by alyssakelley** [comment]
Sorry if this answer is obvious, but why are you starting the file path with ./. ? and would this file path be going to a file named "config.yml" (assuming you meant .yml and not .tml) and not their app.yml be what we are reading from? I think I remember you saying you wanted to change this, but I just want to clarify.

**Comment by slively** [comment]
this is solved correctly on the updates branch
